# Generated by Django 4.1 on 2023-07-06 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Smart_Parking_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="cnic_no",
            field=models.CharField(default=django.utils.timezone.now, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reserve",
            name="license_no",
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
